// Generated by CIRCT firtool-1.75.0
module IntXbar_i1_o1(	// @[generators/rocket-chip/src/main/scala/interrupts/Xbar.scala:22:9]
  input  auto_anon_in_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output auto_anon_out_0	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  assign auto_anon_out_0 = auto_anon_in_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Xbar.scala:22:9]
endmodule

