// Generated by CIRCT firtool-1.75.0
module PLICFanIn(	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:338:7]
  input  io_prio_0,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:339:14]
  input  io_ip,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:339:14]
  output io_dev,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:339:14]
  output io_max	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:339:14]
);

  wire [1:0] effectivePriority_1 = {io_ip, io_prio_0};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:355:100]
  assign io_dev = &effectivePriority_1;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:338:7, :351:{20,57}, :355:100, generators/rocket-chip/src/main/scala/util/Misc.scala:35:36]
  assign io_max = (&effectivePriority_1) & io_prio_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:338:7, :351:20, :355:100, generators/rocket-chip/src/main/scala/util/Misc.scala:35:9]
endmodule

